### ISSUE TITLE
Conflicting HelpMojo error when executing mvn test

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-maven-plugin#123]
When executing `mvn test` on the latest code, I'm getting the following error:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-plugin-plugin:3.9.0:descriptor (default-descriptor) on project spdx-maven-plugin: Error extracting plugin descriptor: 'Goal: help already exists in the plugin descriptor for prefix: spdx
[ERROR] Existing implementation is: org.spdx.spdx_maven_plugin.HelpMojo
[ERROR] Conflicting implementation is: org.spdx.maven.HelpMojo'
```

Maven version is 3.6.3

Attached is the full Maven output with the `-X` option: 
[mvnoutput.txt](https://github.com/spdx/spdx-maven-plugin/files/12264606/mvnoutput.txt)

**Comment by goneall** [comment]
@hboutemy - any ideas?  I did a quick look through the pom file and code and didn't see any obvious conflicts.

**Comment by hboutemy** [comment]
I can't reproduce. I suppose it's a conflict between an old run with older `maven-plugin-plugin` and current run with latest `3.9.0` (that has changed help mojo generation strategy)
just doing a `mvn clean` should solve the issue

**Comment by goneall** [comment]
Thanks @hboutemy for looking into it.  I'm glad it's just me ;).  I also suspect this is something in my local environment since the Github action runs successfully.

I did a clean and upgraded to JDK 17 - same problem.  I'm thinking I should just wipe out my local maven repo and re-download all the dependencies and plugins and see if that fixes it.

**Comment by goneall** [comment]
Cleaned up the development environment - it's now working.

Closing the issue.
