### ISSUE TITLE
add spdx.skip parameter

### ISSUE THREAD

**Issue by hboutemy** [spdx/spdx-maven-plugin#126]
this is a usual flexibility in Maven plugins that is currently missing

**Comment by goneall** [comment]
@hboutemy - Can you describe how the parameter would work?  Would it just skip the entire construction of the SPDX file?  Alternatively, feel free to create a PR if it's easier to answer in Java code ;)

**Comment by hboutemy** [comment]
Yes, no worries, I intend to implement it Sent from Android deviceLe 27 août 2023 01:01, goneall ***@***.***> a écrit :
@hboutemy - Can you describe how the parameter would work?  Would it just skip the entire construction of the SPDX file?  Alternatively, feel free to create a PR if it's easier to answer in Java code ;)
