### ISSUE TITLE
Documentation does not agree with current release

### ISSUE THREAD

**Issue by sebbASF** [spdx/spdx-maven-plugin#132]
The lates release is 0.7.0, but the docs at http://spdx.github.io/spdx-maven-plugin/createSPDX-mojo.html relate to 0.7.1-SNAPSHOT.
This gives a misleading impression of the available parameters, for example spdx.skip is not in 0.7.0, but the doc does not make it clear that it is only available from 0.7.1.

**Comment by hboutemy** [comment]
ou're right, I forgot to add `@since` in #130, I'll do a new PR to fix that
