### ISSUE TITLE
useArtifactID does not apply consistently to all dependencies

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-maven-plugin#142]
Some of the dependency project names still use the name field even though `useArtifactID` is set to `true`.

[See issue 136](https://github.com/spdx/spdx-maven-plugin/issues/136#issuecomment-1862899518) comment for reference.

Attached is an example output - note the "Apache Commons Lang" name in the output.

[org.spdx_java-spdx-library-1.1.11-SNAPSHOT.spdx.json](https://github.com/spdx/spdx-maven-plugin/files/13719322/org.spdx_java-spdx-library-1.1.11-SNAPSHOT.spdx.json)

**Comment by Ali0600** [comment]
Hello @goneall, would it be possible so that **all** the packages use the artifactID? So for like Apache Commons Lang, the name should be something like "org.apache.commons:commons-lang3", etc.

**Comment by goneall** [comment]
@Ali0600 - Please take a look at the file uploaded to PR #143 - I think this matches what you are looking for, but I would like you to review it to make sure.

**Comment by Ali0600** [comment]
I just took a look, this is perfect!

**Comment by goneall** [comment]
Thanks @Ali0600 for the review - I'll spin a new release once I get to a reliable network.
