### ISSUE TITLE
Dependency graph

### ISSUE THREAD

**Issue by rogelio-o** [spdx/spdx-maven-plugin#151]
All the dependencies, including the transient ones, are currently related to the package representing the scanned pom. There exists a dependency hierarchy that we are losing, though. For instance, `junit` depends on `hamcrest-core`, `spdx-maven-plugin-test` depends on `junit`, but `spdx-maven-plugin-test` depends on `hamcrest-core` transitively and not directly.

The following is a visual representation of the [spring-petclinic's](https://github.com/spring-projects/spring-petclinic) SPDX without and with the whole dependency graph:

![image](https://github.com/spdx/spdx-maven-plugin/assets/1966512/950324a4-90dc-4dd6-b3ac-0736c575d5ac)

![image](https://github.com/spdx/spdx-maven-plugin/assets/1966512/cf910706-ee3f-4269-877c-736ac4b5c95b)

As you can see, including the proper relationships is good to have a complete picture, and, at the same time, it is vital to apply VEX statements properly. For instance, a VEX statement can describe a vulnerability affecting `hamcrest-core` that has been mitigated in `junit`; if we don't have the relationship `junit->hamcrest-core`, we cannot know that the vulnerability does not impact the project.

I propose to use the component that the `dependency:tree` plugin uses: the dependency graph builder. We can iterate over the resultant graph to add the SPDX packages and relationships.

**Comment by goneall** [comment]
@rogelio-o the dependencies you mention in the example above are test scoped dependencies.  Do we want to include those or only the compile and runtime? For the use case where we just want the SBOM for the delivered package, the test dependencies are not needed and may create a more complex SBOM for the consumer to interpret.

If we do want to include the test dependencies, we should use the SPDX relationship `TEST_DEPENDENCY_OF`.  Perhaps another option in the configuration as well.

**Comment by rogelio-o** [comment]
@goneall, that's right. Filtering the test dependencies via configuration is definitely helpful. I can include it in the open MR or open a new one for that (the plugin currently adds testing dependencies as it does in my open MR).

I may have used the wrong example with testing dependencies, but my point concerns transitive dependencies. In short, it would be helpful to relate the transitive dependencies with their direct parent instead of with the scanned maven project. Thus, we can have a complete dependency graph, as shown above.

**Comment by goneall** [comment]
@rogelio-o - You can ignore my comment / question above - it is only related to the example used.  After reviewing the code I realized we already include the test dependencies but use the `TEST_DEPENDENCY_OF` relationship to distinguish them from dependencies that may be in the execution path.

Creating the complete dependency graph will definitely create a more accurate and useful SBOM.

Thanks for working on this.
