### ISSUE TITLE
version 0.7.3 is not available in maven central repo

### ISSUE THREAD

**Issue by manojbsw** [spdx/spdx-maven-plugin#155]
Team,
    We are planning to use the fixes done in version 0.7.3 but it is not available in maven central repo.  Can it be push to central repo?

**Comment by goneall** [comment]
@manojbsw - There's one more pull request I'd like to get in before the next release / push to central.  I'll spin a release as soon as I can get the pull request to pass the CI - may take a day or two.

**Comment by goneall** [comment]
I just published release 0.7.3 to Maven Central - it may take a couple hours to become available

**Comment by manojbsw** [comment]
Thanks @goneall

**Comment by manojbsw** [comment]
@goneall - This is yet not published to maven central repo.

**Comment by goneall** [comment]
@manojbsw - see https://central.sonatype.com/artifact/org.spdx/spdx-maven-plugin

It looks like 0.7.3 is published and is the latest version.
