### ISSUE TITLE
.spdx extension impractical

### ISSUE THREAD

**Issue by ppalaga** [spdx/spdx-maven-plugin#16]
SPDX documents get deployed to Maven Central with the `.spdx` extension. This is impractical, because:

* The files are served with `Content-Type: application/octet-stream` by Maven Central and browsers download them instead of rendering them
* When opened in common editors, they are not handled as XML (syntax highlighting, folding, ...)

I wonder if the `.spdx` extension is prescribed by the SPDX spec? Could it eventually get changed to `.spdx.xml` ?

**Comment by goneall** [comment]
The spec states .spdx for tag/value format.  Since this is an RDF/XML format, the suggested extension is *-spdx.rdf.  

@ppalaga how about *-spdx.rdf.xml or *.spdx.rdf.xml?  That should allow it to be rendered properly.

**Comment by ppalaga** [comment]
I am fine with anything ending with `.xml`. 

As for `-spdx.rdf.xml` vs. `.spdx.rdf.xml`, both would solve the problems sketched above, but there is maybe another perspective that might be important here: As you may know, Maven has notions of type and classifier. Together with groupId, artifactId and version, they unambiguously identify an artifact deployed to a Maven repository. See e.g. https://maven.apache.org/pom.html#Dependencies 

Four of those five parts are used to produce the name of the file. The template is `{artifactId}-{version}-{classifier}.{type}`. So the question is whether we want `spdx` to be classifier or a part of the extension?

To decide that, the most important concern seems to be whether two files having different classifiers (e.g. `myartifact-1.2.3-jdk8.jar` and `myartifact-1.2.3-jdk11.jar`) will ever have two separate spdx documents attached. If yes, we should make spdx a part of extension (`myartifact-1.2.3-jdk8.spdx.rdf.xml` and `myartifact-1.2.3-jdk11.spdx.rdf.xml`) if not, we may make it a classifier (`myartifact-1.2.3-spdx.rdf.xml`)

**Comment by goneall** [comment]
Currently, we do not create different SPDX documents for different classifiers.  That being said, we may do that in the future so I'll go with the extension `.spdx.rdf.xml`.

I'll try to spin a new release with this change over the next couple of days.

**Comment by goneall** [comment]
Resolved with PR #17
