### ISSUE TITLE
Make SpdxProjectInformation public

### ISSUE THREAD

**Issue by anddann** [spdx/spdx-maven-plugin#22]
First, thx a lot for this project! It really helped me to understand the SPDX specification wrt. to Maven.
Currently, I'm playing around with the code.
However, exists a reason for ```SpdxProjectInformation``` to be package-private?

**Comment by goneall** [comment]
@anddann Sorry about the delay in response - somehow I missed the issue notice.

I don't see any reason `SpdxProjectInformation` couldn't be made public.  Feel free to submit a PR if you would like it changed.

**Comment by anddann** [comment]
Sry, for the delay. I just opened a PR #23

**Comment by goneall** [comment]
@anddann Thanks for the PR - just merged it.
