### ISSUE TITLE
Running behind corporate proxy

### ISSUE THREAD

**Issue by nhtones** [spdx/spdx-maven-plugin#26]
Hi,
I'm attempting to run this plugin behind a corporate proxy and running into significant performance problems due to connectivity issues. 

It does not appear that there is anyway to configure specific Proxy settings at the plugin level and attempts to add proxy config as JVM variables or MVN_OPTS have not had any impact.

An alternative solution would be to provide a means of suppressing the attempt to access license files directly and allow local paths to license files to be supplied via parameter?

This may be an issue with the core SPDX library and also has an impact on the CycloneDX plugin that shares core code.

Sample log output

[DEBUG] System architecture: 64 bit
[DEBUG] open(http://spdx.org/licenses/index.html)
[DEBUG] Not mapped: http://spdx.org/licenses/index.html
[DEBUG] [1] GET http://spdx.org/licenses/index.html
[DEBUG] Connection request: [route: {}->http://spdx.org][total kept alive: 0; route allocated: 0 of 2; total allocated: 0 of 20]
[DEBUG] Connection leased: [id: 0][route: {}->http://spdx.org][total kept alive: 0; route allocated: 1 of 2; total allocated: 1 of 20]
[DEBUG] Connecting to spdx.org/54.192.87.111:80
[DEBUG] Connect to spdx.org/54.192.87.111:80 timed out. Connection will be retried using another IP address
[DEBUG] Connecting to spdx.org/54.192.87.119:80
[DEBUG] Connect to spdx.org/54.192.87.119:80 timed out. Connection will be retried using another IP address
[DEBUG] Connecting to spdx.org/54.192.87.79:80
[DEBUG] Connect to spdx.org/54.192.87.79:80 timed out. Connection will be retried using another IP address
[DEBUG] Connecting to spdx.org/54.192.87.60:80
[DEBUG] http-outgoing-0: Shutdown connection
[DEBUG] Connection discarded
[DEBUG] http-outgoing-0: Close connection
[DEBUG] Connection released: [id: 0][route: {}->http://spdx.org][total kept alive: 0; route allocated: 0 of 2; total allocated: 0 of 20]
log4j:WARN No appenders could be found for logger (org.spdx.rdfparser.license.ListedLicenses).
log4j:WARN Please initialize the log4j system properly.
[DEBUG] open(resources/stdlicenses/index.html)
[DEBUG] Not mapped: resources/stdlicenses/index.html
[DEBUG] Found: resources/stdlicenses/index.html (ClassLoaderLocator)
[ERROR] Rewired RDFReaderFImpl - configuration changes have no effect on reading
[ERROR] Rewired RDFReaderFImpl - configuration changes have no effect on reading
[DEBUG] Connection manager is shutting down
[DEBUG] Connection manager shut down
[DEBUG] open(https://spdx.org/licenses/CC0-1.0)
[DEBUG] Not mapped: https://spdx.org/licenses/CC0-1.0
[DEBUG] [2] GET https://spdx.org/licenses/CC0-1.0
[DEBUG] Connection request: [route: {}->https://spdx.org][total kept alive: 0; route allocated: 0 of 2; total allocated: 0 of 20]
[DEBUG] Connection leased: [id: 1][route: {}->https://spdx.org][total kept alive: 0; route allocated: 1 of 2; total allocated: 1 of 20]
[DEBUG] Connecting to spdx.org/54.192.87.111:443
[DEBUG] Connect to spdx.org/54.192.87.111:443 timed out. Connection will be retried using another IP address
[DEBUG] Connecting to spdx.org/54.192.87.119:443
[DEBUG] Connect to spdx.org/54.192.87.119:443 timed out. Connection will be retried using another IP address
[DEBUG] Connecting to spdx.org/54.192.87.79:443
[DEBUG] Connect to spdx.org/54.192.87.79:443 timed out. Connection will be retried using another IP address
[DEBUG] Connecting to spdx.org/54.192.87.60:443
[DEBUG] http-outgoing-1: Shutdown connection
[DEBUG] Connection discarded
[DEBUG] http-outgoing-1: Close connection
[DEBUG] Connection released: [id: 1][route: {}->https://spdx.org][total kept alive: 0; route allocated: 0 of 2; total allocated: 0 of 20]

**Comment by goneall** [comment]
If you set the property `SPDXParser.OnlyUseLocalLicenses` to `true` it will use a cached version of the license list and not go over the internet.  This is implemented in the core library so it should work for CycloneDX as well.

I have not tried this option in the maven plugin, but I believe it should work if the property value is passed in as a JVM parameter.

@nhtones - if you could give this a try and let me know if it works.

**Comment by nhtones** [comment]
@goneall 
Ha - I was just coming on to update this issue with that exact finding... Having pulled down CycloneDX and SPDX-Tools.  Wish I had seen you comment earlier!

I can confirm that applying the SPDXParser.OnlyUseLocalLicenses=true system property suppresses the attempts to retrieve license documents.

I have tried this at execution time as a system property and also at build time as part of my POM.xml using the maven-properties-plugin.

This has seen builds return to normal execution times, 8 minutes instead of the 4+ hours we were seeing!

Would be nice to have this as a configurable property of SDPX maven plugin but this work around helps

**Comment by amCap1712** [comment]
I think #34 has resolved this.

**Comment by goneall** [comment]
Thanks @amCap1712 - I'll close this as resolved
