### ISSUE TITLE
Adopt and enforce code style in project code base

### ISSUE THREAD

**Issue by amCap1712** [spdx/spdx-maven-plugin#33]
While working on the code base, I found that the code style is inconsistent. This includes trailing white spaces, placement of braces and so on. This creates unnecessary noise in git diffs when different people work on the code. It makes sense to adopt a code style guide for the project. If one of the other SPDX projects use a style guide, it can be adopted for this project as well.

Otherwise, one of the many standard code styles exist for Java including [Google Java Style Guide](https://google.github.io/styleguide/javaguide.html), [OpenJDK Java Style Guidelines](http://cr.openjdk.java.net/~alundblad/styleguide/index-v6.html) and so on may be used. Tools like checkstyle can be used to enforce the code style guidelines if necessary as well.

**Comment by goneall** [comment]
This particular project should be using the [Maven code style](https://maven.apache.org/developers/conventions/code.html).  I see that this isn't document - we should add this to the README.  I notice the repo doesn't have a CONTRIBUTING.MD file - we should probably add that as well.

In terms of enforcement, I don't know if there is a Travis-CI type script we an run, but there are some IDE code styles referenced on the Maven code style documentation page.

**Comment by goneall** [comment]
I'll create a PR to document the coding style.

**Comment by goneall** [comment]
@amCap1712 I added PR #35 to document the coding style.  I'm thinking that should be sufficient for this issue unless you know of a style checker we should use as part of the Travis-CI script.

**Comment by amCap1712** [comment]
I think the [Maven Checkstyle Plugin](https://maven.apache.org/plugins/maven-checkstyle-plugin/index.html) can be used for this purpose. It'll need to configured to use the maven code style as it supports only Google and Sun by default. I'll take a look it and make the necessary changes.

**Comment by goneall** [comment]
I did some research and couldn't find any easy way to use the Maven Checkstyle for the recommended Maven style, so I'm closing this issue.  @amCap1712 - if you do find a way to check styles for the Maven coding style, please open a new issue or PR.
