### ISSUE TITLE
Support for JSON formatted SPDX document?

### ISSUE THREAD

**Issue by jdolitsky** [spdx/spdx-maven-plugin#46]
Just used this plugin (thank you!) and the outputted SBOM was in XML format. Is there some option to get this in JSON format?

**Comment by goneall** [comment]
> Is there some option to get this in JSON format?

Not currently.  Should be an easy enhancement.

I'll need to update the plugin for the 2.3 release of the spec over the next month or so.  I'll try to add that in during that release.  The upgrade to 2.3 will require some significant refactoring, so this should be a relatively small increment.

I'm thinking we just add a configuration element `<spdxFormat>` that would be one of `JSON`, `YAML` or `RDF/XML` initially.  Default to `RDF/XML` for compatibility.  We could add `TAG/VALUE` and even `XLSX`, but it would add quite a few additional dependencies which may not be desirable.

**Comment by jdolitsky** [comment]
> I'm thinking we just add a configuration element <spdxFormat> that would be one of JSON, YAML or RDF/XML initially

That sounds great!
