### ISSUE TITLE
Should this plugin be generating sbom data about a project's dependencies?

### ISSUE THREAD

**Issue by patflynn** [spdx/spdx-maven-plugin#60]
Hi there,

When I run createSPDX the resulting .spdx.json only includes metadata of the top level project and its files, but nothing about the dependencies. I was just wondering if this is WAI or whether I have it misconfigured somehow. 

thanks!

**Comment by goneall** [comment]
@patflynn The plugin should generate some metadata about the dependency packages if they are compile time dependencies.  The level of details depends on how much information is present in the dependency POM file.  If the dependency has an SPDX file, it will use an [External Document Reference](https://spdx.github.io/spdx-spec/v2.3/document-creation-information/#66-external-document-references-field) for the SPDX file instead of having the metadata in the generated SPDX file.

If there is a compile time dependency and no package information is present, it could be an issue with the plugin.

**Comment by patflynn** [comment]
thanks @goneall .  Perhaps I have it misconfigured?  Here's a [PR](https://github.com/patflynn/jib-sbom-demo/pull/1/files) with it enabled and a copy of the resulting output but without any included deps.

**Comment by patflynn** [comment]
perhaps the issue is that the spring boot dep isn't explicitly `<scope>compile</scope>`?

**Comment by goneall** [comment]
@patflynn It looks like the dependencies are in the output SPDX file.  For example:

```
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
```
produces:
```
  "packages" : [ {
    "SPDXID" : "SPDXRef-gnrtd0",
    "comment" : "This package was created for a Maven dependency.  No SPDX or license information could be found in the Maven POM file.",
    "copyrightText" : "NOASSERTION",
    "filesAnalyzed" : false,
    "licenseConcluded" : "NOASSERTION",
    "licenseDeclared" : "NOASSERTION",
    "name" : "spring-boot-starter-web",
    "versionInfo" : "2.7.4"
  },
```

and 

```
 "relationships" : [ {
    "spdxElementId" : "SPDXRef-gnrtd2",
    "relationshipType" : "DYNAMIC_LINK",
    "relatedSpdxElement" : "SPDXRef-gnrtd0",
    "comment" : "Relationship based on Maven POM file dependency information"
  }
```

**Comment by patflynn** [comment]
oh I see! Sorry I was blind! The issue is that I was expecting to see the full transitive dep list, and the list was so much shorter than the [cyclonedx output](https://github.com/patflynn/jib-sbom-demo/blob/main/cyclone-dx-out/bom.json) I assumed there was nothing there.   Will outputting the full transitives deps at some point be an option?

**Comment by goneall** [comment]
> Will outputting the full transitives deps at some point be an option?

It would be nice to include the transitive dependencies.  Do you want to rename this issue or open a new one to track?

**Comment by patflynn** [comment]
SG. I'll close and create a new one. Sorry about the noise, doing too many things at once. :)
