### ISSUE TITLE
Maven properties are not inherited properly

### ISSUE THREAD

**Issue by alerosmile** [spdx/spdx-maven-plugin#70]
For the main artifact, the plugin reads the package information from `MavenProject`. For the dependencies, the plugin reads the pom.xml directly. For this reason, the package information is incomplete because all inherited properties are missing.

Many artifacts do not define a version because it is inherited from the parent. This version information is therefore missing in the resulting SPDX file.

**Comment by goneall** [comment]
@alerosmile Good point and agree we should include information inherited from the parent.  Do you have any suggestions on how to design/implement this?

**Comment by goneall** [comment]
@alerosmile Thanks for the research!

It looks like we can use the Maven model builder directly.  I'll do some experimentation over the next week or so.

**Comment by alerosmile** [comment]
There seems to be a much easier solution for this: https://stackoverflow.com/a/39609354

**Comment by goneall** [comment]
@alerosmile this is much simpler - thanks!

I created a PR with the changes: PR #72 

If you could review the pull request and let me know if you see anything wrong.

Also - if you can provide me with a good example set of POM files and expected behavior, I'll create a unit test to verify.

**Comment by alerosmile** [comment]
I'll have to make up an example for this. But probably not before next year, sorry.

**Comment by alerosmile** [comment]
@goneall - I've created a simple test project where some properties are inherited in different ways. You can try to build the artifact project with the config.site-snapshots profile activated or not - it works as expected now.

[depTest.zip](https://github.com/spdx/spdx-maven-plugin/files/10345951/depTest.zip)

**Comment by goneall** [comment]
Thanks @alerosmile 

I'll see if I can work this into a unit test.

In the mean time, I'll go ahead and merge PR #72 since it looks like it does fix this issue.
