### ISSUE TITLE
Add a separate goal which does not invoke any other lifecycle

### ISSUE THREAD

**Issue by alerosmile** [spdx/spdx-maven-plugin#71]
The `createSPDX` always invokes the execution of the lifecycle phase `verify` prior to executing itself. Is that really necessary? If the goal is configured in the pom, the verify phase runs twice.

You could add a separate goal `createSPDX-no-fork' which does not invoke any other lifecyle (similar to the [(javadoc:javadoc-no-fork)](https://maven.apache.org/plugins/maven-javadoc-plugin/javadoc-no-fork-mojo.html) goal).

**Comment by goneall** [comment]
@alerosmile I'm assuming adding a separate goal would be compatible with the current usage.  If it is compatible, would you mind creating a pull request to add the additional lifecycle?  `createSPDX-no-fork` sounds like a reasonable name to me.

**Comment by alerosmile** [comment]
I could do that, but I think we have some other issue here.

I'm guessing that the `verify` phase is executed to create the jar file first so it can be included in the SPDX file, right? But calling `mvn spdx:createSPDX` creates an SPDX file without the package info from the project (`[WARNING] Null package file`). This is because Maven creates a clone of the project for the forked lifecycle execution. The jar plugin then attaches the .jar file as the main artifact to this clone and not to the actual project resulting in [mainArtifact.getFile()](https://github.com/spdx/spdx-maven-plugin/blob/325ea55c087106eb9f7c486499c261197e62fd97/src/main/java/org/spdx/maven/CreateSpdxMojo.java#L921) returning `null`.

Calling `mvn verify spdx:createSPDX` creates an SPDX file including the package info but executes the `verify` phase twice.

Calling `mvn verify spdx:createSPDX-no-fork` works best here.

Even though it's not compatible with current usage, I think we should change the behavior of `createSPDX` target as it gives unexpected results.

**Comment by goneall** [comment]
> I'm guessing that the `verify` phase is executed to create the jar file first so it can be included in the SPDX file, right?

I think you're right.  It has been a while since I wrote the code, so I don't recall the exact reason, only that it solved an issue.

> Even though it's not compatible with current usage, I think we should change the behavior of createSPDX target as it gives unexpected results.

Agree the current implementation isn't ideal.  The main usage I care about is that a `mvn clean install` will generate an SPDX document if it is property configured in the POM file.

**Comment by goneall** [comment]
@alerosmile Am I correct in understanding that changing the behavior of the current goal will create `mvn clean install`.

If so, should we create a goal `createSPDX-no-fork` that we can use the command `mvn verify spdx:createSPDX-no-fork` and document the behaviors?

**Comment by alerosmile** [comment]
@goneall This has been fixed in #79
