### ISSUE TITLE
The plugin no longer builds and runs with Java 8

### ISSUE THREAD

**Issue by garydgregory** [spdx/spdx-maven-plugin#76]
The jar `spdx-rdf-store` seems to be compiled to Java 11?

This POM says Java 8 but running `mvn clean install` for this plugin says:
```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /C:/Users/ggregory/git/g/spdx-maven-plugin/src/main/java/org/spdx/maven/SpdxDependencyInformation.java:[69,29] cannot access org.spdx.spdxRdfStore.RdfStore
  bad class file: C:\Users\ggregory\.m2\repository\org\spdx\spdx-rdf-store\1.1.3\spdx-rdf-store-1.1.3.jar(org/spdx/spdxRdfStore/RdfStore.class)
    class file has wrong version 55.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.531 s
[INFO] Finished at: 2023-02-04T10:18:15-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project spdx-maven-plugin: Compilation failure
[ERROR] /C:/Users/ggregory/git/g/spdx-maven-plugin/src/main/java/org/spdx/maven/SpdxDependencyInformation.java:[69,29] cannot access org.spdx.spdxRdfStore.RdfStore
[ERROR]   bad class file: C:\Users\ggregory\.m2\repository\org\spdx\spdx-rdf-store\1.1.3\spdx-rdf-store-1.1.3.jar(org/spdx/spdxRdfStore/RdfStore.class)
[ERROR]     class file has wrong version 55.0, should be 52.0
[ERROR]     Please remove or make sure it appears in the correct subdirectory of the classpath.
[ERROR]
[ERROR] -> [Help 1]
```

Ah... the problems seems to be an eager update to Apache Jena, building `spdx-rdf-store` with Java 8 yields:
```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /C:/Users/ggregory/git/g/spdx-java-rdf-store/src/main/java/org/spdx/spdxRdfStore/RdfStore.java:[38,29] cannot access org.apache.jena.graph.Node
  bad class file: C:\Users\ggregory\.m2\repository\org\apache\jena\jena-core\4.7.0\jena-core-4.7.0.jar(org/apache/jena/graph/Node.class)
    class file has wrong version 55.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
```
Please go back to supporting Java 8 or make it obvious that Java 11 is required.

**Comment by goneall** [comment]
@garydgregory Thanks for pointing out the inconsistency.  One of the dependencies required Java 11 (previous versions of the dependency have security vulnerabilities), so I'll update the POM file  to require Java 11.

**Comment by goneall** [comment]
@garydgregory Could you look at PR #77 and let me know if this resolves the issue.

Note that the dependency is only required if we're outputting RDF format SPDX.  For JSON, I think (but need to verify) we can continue to use Java 1.8.

If using Java 11 is a significant issue, perhaps we can explore a way of making the RDF format a more optional dependency.  Not quite sure how we would do that, but let me know if you have any thoughts.

**Comment by garydgregory** [comment]
Hi @goneall 
I commented in the PR. Whichever Java version you require is up to you ;-) For us over at Apache Commons that means that if Java 11 is required we will have to run release builds using Java 11 instead of 8 which will end up being a problem likely if a component uses the NIO Buffer APIs where methods move from Java version to version in the hierarchy. I've only encountered the need for Java 11 with the spdx plugin when running a multi-module build, never in a simple Maven project. Eventually we will migrate to Java 11 but there are no immediate plans.

**Comment by goneall** [comment]
@garydgregory - Are you using the RDF format for your output or just JSON?  If JSON, then the library causing the problem isn't really being used.

BTW - Apache Jena is the library which is requiring the upgrade in Java versions.  Jena versions which use Java 8 have a security vulnerability which I though might impact downstream users.
