### ISSUE TITLE
Suggest: Create SPDX file with artifactId as name

### ISSUE THREAD

**Issue by hen** [spdx/spdx-maven-plugin#8]
The SPDX file is created with the <name> as the filename. This is intended to be a human readable name, my suggestion is to use the full:

```
<groupId>.<artifactId>-<version>.spdx
```

or at least the <artifactId>-<version>.spdx

**Comment by goneall** [comment]
Agree with the suggestion.  I plan to update the tool to export a separate SPDX document for each of the artifact files generated by the Maven.  I'll rename the files in the same pattern as the digital signature files (e.g. project.jar -> project.jar.spdx; project-sources.jar -> project-sources.jar.spdx).  It will likely take me until Mid Oct. to make these changes.
